branch

diff --git a/.github/workflows/create_rc_branch.yml b/.github/workflows/create_rc_branch.yml
--- a/.github/workflows/create_rc_branch.yml
+++ b/.github/workflows/create_rc_branch.yml
@@ -45,7 +45,7 @@ jobs:
         workiz_actions_commit_sha="${workiz_actions_commit_sha#\"}"
         echo "workiz_actions_commit_sha $workiz_actions_commit_sha"
 
-        git_refs_response2=$(
+        git_refs_response=$(
         curl -s -X POST https://api.github.com/repos/Workiz/workiz-actions/git/refs \
         -H "Authorization: token $GITHUB_TOKEN" \
         -d @- << EOF
@@ -56,6 +56,16 @@ jobs:
         }
         EOF
         )
+
+        git_ref_posted=$( echo "${git_refs_response}" | jq .ref | tr -d '"' )
+
+        echo "::debug::${git_refs_response}"
+        if [ "${git_ref_posted}" = "refs/heads/${BACKEND_BRANCH}" ]; then
+        exit 0
+        else
+        echo "::error::Branch was not created properly."
+        exit 1
+        fi
      
   build-rc-env:
     needs: [create-rc-branch]
