test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,28 +1,37 @@
 name: test
 on:
-  workflow_dispatch:
-  # schedule:
-  #   - cron:  '*/5 * * * *'
+  push:
+  schedule:
+    - cron:  '*/5 * * * *'
 
 jobs:
 
-  job1:
+  check-github-actor:
+    name: check github actor
     runs-on: ubuntu-latest
     steps:
-    - run: |-
-        status=$(curl --location --request GET 'https://infra-api.workiz.com/releaseProgress/get_train_status/' \
-        --header 'WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}' | jq .'status')
-        echo "$status"
-        if ! $status ; then
-            echo "Error - train is lock now"
-            exit 1
-        fi
-  job2: 
-    needs: [job1]
-    runs-on: ubuntu-latest
-    steps:
-    - run: |-
-        echo "test"
+    - run: | 
+        echo "${{ github.actor }}"
+    - name: Checkout shared actions
+      uses: actions/checkout@v3
+      with:
+        repository: Workiz/workiz-actions
+        ref: workiz.com
+        token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
+        path: ./tmp/workiz-actions
+    - name: check github actor 
+      uses: ./tmp/workiz-actions/check-github-actor
+      with:
+        GITHUB_ACTOR: ${{ github.actor }}
+    - name: infra-api failed
+      if: failure()  
+      run: | 
+        curl --location --request POST 'https://infra-api.workiz.com/releaseProgress/update_job_status/' \
+        --header 'Content-Type: application/json' \
+        --data-raw '{
+            "job_name" : "rc_deploy",
+            "status" : "failed"
+            }' || echo -e "\e[1;31m infra-api sent failed"
 
   
    
