nehora

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -8,6 +8,7 @@ env:
   GKE_CLUSTER: staging
   GKE_ZONE: us-central1	
   REPO_NAME: workiz-helm-repo-dev
+  NAMESPACE: ${{ env.NAMESPACE }}
 
 
 jobs:
@@ -51,16 +52,16 @@ jobs:
           echo "matrix={\"services\":$RELEASES_JSON}" >> $GITHUB_OUTPUT
       - name: 'create namespace'
         run: |
-          kubectl create namespace nehora || echo "namespace already exists"
+          kubectl create namespace ${{ env.NAMESPACE }} || echo "namespace already exists"
       - name: 'create secrets'
         run: |
-          kubectl get secret gcpsm-secret -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
-          kubectl get secret google-local-key -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
-          kubectl get es api-secret-key -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
-          kubectl get es staging-backend-php-service-accounts-auth-p12 -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
-          kubectl get es staging-backend-php-service-accounts-google-creds -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
-          kubectl get es staging-unit-public-key -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
-          kubectl get es staging-unit-private-key -n staging -o yaml | sed 's/staging/nehora/g' | kubectl apply -n nehora -f - || echo "secret not found"
+          kubectl get secret gcpsm-secret -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+          kubectl get secret google-local-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+          kubectl get es api-secret-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+          kubectl get es staging-backend-php-service-accounts-auth-p12 -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+          kubectl get es staging-backend-php-service-accounts-google-creds -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+          kubectl get es staging-unit-public-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+          kubectl get es staging-unit-private-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
   deploy-service:
     needs: create-staging-env
     runs-on: ubuntu-latest
@@ -102,14 +103,14 @@ jobs:
           echo "Deploying service ${{ matrix.services }}"
           IMAGE=$(helm get values ${{ matrix.services }} --namespace staging | grep 'tag:' | awk '{print $2}')
           STAGING_NAMESPACE="staging"
-          TARGET_NAMESPACE="nehora"
+          TARGET_NAMESPACE="${{ env.NAMESPACE }}"
           CHART_REPO="workiz-helm-repo-dev/workiz-chart"
           SECRET_PROJECT_ID="workiz-development"
           TIMEOUT="300s"
           echo "Image: $IMAGE"
           echo "Deploying ${{ matrix.services }}"
           helm get values ${{ matrix.services }} --namespace staging -o yaml > existing-values.yaml
-          sed -i 's/environment: staging/environment: nehora/g' existing-values.yaml
+          sed -i 's/environment: staging/environment: ${{ env.NAMESPACE }}/g' existing-values.yaml
 
           helm upgrade ${{ matrix.services }} $CHART_REPO --namespace $TARGET_NAMESPACE --set secretProjectId=$SECRET_PROJECT_ID --values existing-values.yaml --atomic --timeout $TIMEOUT --devel --install --debug \
           --set secretProjectId=workiz-development \
@@ -156,10 +157,13 @@ jobs:
       - name: 'Deploy backend-php'
         run: |
           APP_VERSION=$(helm get values backend-php-staging --namespace staging | grep 'tag:' | awk '{print $2}')
-          K8S_NAMESPACE="nehora"
+          K8S_NAMESPACE="${{ env.NAMESPACE }}"
           cp .htaccess ./infra/helm/workiz-backend/backend-base 
           helm dependency update ./infra/helm/staging-dev
-          helm upgrade --install -n $K8S_NAMESPACE backend-php-staging-dev \
+          # replace all staging-dev to ${{ env.NAMESPACE }} in file infra/helm/staging-dev/values.staging-dev.yaml
+          sed -i 's/staging-dev/$K8S_NAMESPACE/g' infra/helm/staging-dev/values.staging-dev.yaml
+          cat infra/helm/staging-dev/values.staging-dev.yaml
+          helm upgrade --install -n $K8S_NAMESPACE backend-php-$K8S_NAMESPACE \
               ./infra/helm/staging-dev \
               -f infra/helm/staging/values.staging.yaml \
               -f infra/helm/staging-dev/values.staging-dev.yaml \
@@ -169,7 +173,7 @@ jobs:
               --set global.image.tag=$APP_VERSION \
               --set global.githubRef="bgfdmkl" \
               --set global.githubSha="${APP_VERSION}" \
-              --set namespace="nehora" \
+              --set namespace=$K8S_NAMESPACE   \
               --set staging-dev.namespace=$K8S_NAMESPACE \
               --set base.namespace=$K8S_NAMESPACE \
               --set staging.namespace=$K8S_NAMESPACE \
