nehora

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -12,56 +12,56 @@ env:
 
 
 jobs:
-  create-staging-env:
-    permissions:
-      contents: 'read'
-      id-token: 'write'
-    runs-on: ubuntu-latest
-    outputs:
-      matrix: ${{ steps.matrix.outputs.matrix }}
-    steps:
-      - name: Authenticate to Google Cloud
-        uses: google-github-actions/auth@v2
-        with:
-          workload_identity_provider: projects/791610978826/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
-          service_account: github-actions-service-account@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
-      - name: 'Set up Cloud SDK'
-        uses: 'google-github-actions/setup-gcloud@v2'
-      - uses: google-github-actions/get-gke-credentials@v2
-        with:
-          cluster_name: ${{ env.GKE_CLUSTER }}
-          location: ${{ env.GKE_ZONE }}
-      - id: 'secrets'
-        uses: 'google-github-actions/get-secretmanager-secrets@v2'
-        with:
-          secrets: |-
-            GH_READONLY_TOKEN:${{ env.PROJECT_ID }}/GH_READONLY_TOKEN
-            AZURE_HELM_VERSION:${{ env.PROJECT_ID }}/AZURE_HELM_VERSION
-            WORKIZ_INFRA_AUTH:${{ env.PROJECT_ID }}/WORKIZ_INFRA_AUTH
-            MARKIZBOT_COMMENT_TOKEN:${{ env.PROJECT_ID }}/MARKIZBOT_COMMENT_TOKEN
-      - uses: azure/setup-helm@v4.1.0
-        with:
-          version: ${{ steps.secrets.outputs.AZURE_HELM_VERSION}} 
-      - name: 'create matrix for all services'
-        id: matrix
-        run: |
-          EXCLUDE=("account" "ai-services-exp" "backend-php-pt" "elasticsearch-listener" "mongodb-listener" "socket-io" "ts-service" "infra-api" "infra-api-staging" "qb-desktop" "ai-services" "integrations-exp" "microservice-for-infra-tests" "backend-php-staging")
-          EXCLUDE_JSON=$(printf '%s\n' "${EXCLUDE[@]}" | jq -R . | jq -s .)
-          RELEASES_JSON=$(helm list --namespace staging -o json | jq -c --argjson exclude "$EXCLUDE_JSON" '[.[] | select(.name as $name | $exclude | index($name) | not) | .name]')
-          echo "matrix={\"services\":$RELEASES_JSON}"
-          echo "matrix={\"services\":$RELEASES_JSON}" >> $GITHUB_OUTPUT
-      - name: 'create namespace'
-        run: |
-          kubectl create namespace ${{ env.NAMESPACE }} || echo "namespace already exists"
-      - name: 'create secrets'
-        run: |
-          kubectl get secret gcpsm-secret -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
-          kubectl get secret google-local-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
-          kubectl get es api-secret-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
-          kubectl get es staging-backend-php-service-accounts-auth-p12 -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
-          kubectl get es staging-backend-php-service-accounts-google-creds -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
-          kubectl get es staging-unit-public-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
-          kubectl get es staging-unit-private-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  # create-staging-env:
+  #   permissions:
+  #     contents: 'read'
+  #     id-token: 'write'
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     matrix: ${{ steps.matrix.outputs.matrix }}
+  #   steps:
+  #     - name: Authenticate to Google Cloud
+  #       uses: google-github-actions/auth@v2
+  #       with:
+  #         workload_identity_provider: projects/791610978826/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
+  #         service_account: github-actions-service-account@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
+  #     - name: 'Set up Cloud SDK'
+  #       uses: 'google-github-actions/setup-gcloud@v2'
+  #     - uses: google-github-actions/get-gke-credentials@v2
+  #       with:
+  #         cluster_name: ${{ env.GKE_CLUSTER }}
+  #         location: ${{ env.GKE_ZONE }}
+  #     - id: 'secrets'
+  #       uses: 'google-github-actions/get-secretmanager-secrets@v2'
+  #       with:
+  #         secrets: |-
+  #           GH_READONLY_TOKEN:${{ env.PROJECT_ID }}/GH_READONLY_TOKEN
+  #           AZURE_HELM_VERSION:${{ env.PROJECT_ID }}/AZURE_HELM_VERSION
+  #           WORKIZ_INFRA_AUTH:${{ env.PROJECT_ID }}/WORKIZ_INFRA_AUTH
+  #           MARKIZBOT_COMMENT_TOKEN:${{ env.PROJECT_ID }}/MARKIZBOT_COMMENT_TOKEN
+  #     - uses: azure/setup-helm@v4.1.0
+  #       with:
+  #         version: ${{ steps.secrets.outputs.AZURE_HELM_VERSION}} 
+  #     - name: 'create matrix for all services'
+  #       id: matrix
+  #       run: |
+  #         EXCLUDE=("account" "ai-services-exp" "backend-php-pt" "elasticsearch-listener" "mongodb-listener" "socket-io" "ts-service" "infra-api" "infra-api-staging" "qb-desktop" "ai-services" "integrations-exp" "microservice-for-infra-tests" "backend-php-staging")
+  #         EXCLUDE_JSON=$(printf '%s\n' "${EXCLUDE[@]}" | jq -R . | jq -s .)
+  #         RELEASES_JSON=$(helm list --namespace staging -o json | jq -c --argjson exclude "$EXCLUDE_JSON" '[.[] | select(.name as $name | $exclude | index($name) | not) | .name]')
+  #         echo "matrix={\"services\":$RELEASES_JSON}"
+  #         echo "matrix={\"services\":$RELEASES_JSON}" >> $GITHUB_OUTPUT
+  #     - name: 'create namespace'
+  #       run: |
+  #         kubectl create namespace ${{ env.NAMESPACE }} || echo "namespace already exists"
+  #     - name: 'create secrets'
+  #       run: |
+  #         kubectl get secret gcpsm-secret -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  #         kubectl get secret google-local-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  #         kubectl get es api-secret-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  #         kubectl get es staging-backend-php-service-accounts-auth-p12 -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  #         kubectl get es staging-backend-php-service-accounts-google-creds -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  #         kubectl get es staging-unit-public-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
+  #         kubectl get es staging-unit-private-key -n staging -o yaml | sed 's/staging/${{ env.NAMESPACE }}/g' | kubectl apply -n ${{ env.NAMESPACE }} -f - || echo "secret not found"
   # deploy-service:
   #   needs: create-staging-env
   #   runs-on: ubuntu-latest
@@ -120,7 +120,7 @@ jobs:
   #         --set image.tag=$IMAGE \
   #         --set customNodeEnv=staging 
   deploy-backend-php:
-    needs: create-staging-env
+    # needs: create-staging-env
     runs-on: ubuntu-latest
     permissions:
       contents: 'read'
