add-git-pull-tags

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -6,16 +6,17 @@ on:
 jobs:
 
   send-slack-msg:
+    needs: [create-release]
     name: send slack msg
     runs-on: ubuntu-latest
     steps: 
     - name: Checkout backend
-      uses: actions/checkout@v3
+      uses: actions/checkout@v3 
       with:
         repository: Workiz/backend
         ref: workiz.com
         token: ${{ secrets.GH_TOKEN_REPOS }}
-        path: ./   
+        path: ./
     - name: Checkout frontend
       uses: actions/checkout@v3
       with:
@@ -32,13 +33,14 @@ jobs:
         path: ./tmp/workiz-actions
     - name: get last tag
       run: |
-       git config --global --add safe.directory /github/workspace
+        git config --global --add safe.directory /github/workspace
         git fetch --all
+        git pull --tags
         LAST_TAG=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -1) 
         if [[ "$LAST_TAG" =~ ^v([0-9]\.[0-9]*)$ ]]; then
           echo "${BASH_REMATCH[1]}"
           git checkout workiz.com
-          git push origin --delete rc${BASH_REMATCH[1]}-branch
+          # git push origin --delete rc${BASH_REMATCH[1]}-branch
         fi
         current_branch=$(git rev-parse --abbrev-ref HEAD)
         echo "current branch $current_branch"
@@ -63,11 +65,12 @@ jobs:
         cd ./tmp/frontend
         git config --global --add safe.directory /github/workspace/tmp/frontend
         git fetch --all
+        git pull --tags
         LAST_TAGS=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -1) 
         if [[ "$LAST_TAGS" =~ ^v([0-9]\.[0-9]*)$ ]]; then
           echo "${BASH_REMATCH[1]}"
           git checkout workiz.com
-          git push origin --delete rc${BASH_REMATCH[1]}-branch
+          # git push origin --delete rc${BASH_REMATCH[1]}-branch
         fi
         LAST_TAGS=$(git tag | sort -V | grep -i "^v[0-9]\.[0-9]*$" | tail -2)
         if [[ "$LAST_TAGS" =~ ^(v[a-z0-9\.\-]*).*(v[a-z0-9\.\-]*)$ ]]; then
@@ -99,67 +102,52 @@ jobs:
       uses: ./tmp/workiz-actions/slack-msg
       with:
         CHANNEL: 'nehora'
-        MESSAGE: 'hi all \nrelease is out :slightly_smiling_face: \n you can see release notes in releases channel'
+        MESSAGE: 'hi all \nrelease is out :slightly_smiling_face: \n you can see #release notes in releases channel'
         SUCCESS: true
         WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
-        LINKS: '[{"name" :"frontend","link": " https://github.com/Workiz/frontend/compare/${{env.PREV_TAG}}...v3.350"}]'
-  # create-release:
-  #   name: create-release-from-tag
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout backend
-  #       uses: actions/checkout@v3
-  #     - name: create backend release
-  #       run: | 
-  #         git config --global --add safe.directory /github/workspace
-  #         git fetch --tags
-  #         LAST_TAG=$(git tag | sort -V | grep -i "^v[0-9]\..*" | tail -1)
-  #         git_refs_response=$(
-  #         curl -s -X POST https://api.github.com/repos/Workiz/nehora-test/releases \
-  #         -H "Authorization: token ${{ secrets.GH_TOKEN_REPOS }}" \
-  #         -d @- << EOF
-  #         {
-  #         "tag_name":"$LAST_TAG"
-  #         }
-  #         EOF
-  #         )
-  #         git_ref_posted=$( echo "${git_refs_response}" | jq .tag_name | tr -d '"' )
-  #         echo "::debug::${git_refs_response}"
-  #         if [ "${git_ref_posted}" = "$LAST_TAG" ]; then
-  #         echo "backend release created"
-  #         else
-  #         echo "::error::backend Realse was not created properly."
-  #         exit 1
-  #         fi
-  #     - name: Checkout frontend
-  #       uses: actions/checkout@v3
-  #       with:
-  #         repository: Workiz/nehora
-  #         ref: workiz.com
-  #         token: ${{ secrets.GH_TOKEN_REPOS }}
-  #         path: ./ 
-  #     - name: create frontend release
-  #       run: | 
-  #         git config --global --add safe.directory /github/workspace
-  #         git fetch --tags
-  #         LAST_TAG=$(git tag | sort -V | grep -i "^v[0-9]\..*" | tail -1) 
-  #         echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV 
-  #         git_refs_response=$(
-  #         curl -s -X POST https://api.github.com/repos/Workiz/nehora/releases \
-  #         -H "Authorization: token ${{ secrets.GH_TOKEN_REPOS }}" \
-  #         -d @- << EOF
-  #         {
-  #         "tag_name":"$LAST_TAG"
-  #         }
-  #         EOF
-  #         )
-  #         git_ref_posted=$( echo "${git_refs_response}" | jq .tag_name | tr -d '"' )
-  #         echo "::debug::${git_refs_response}"
-  #         if [ "${git_ref_posted}" = "$LAST_TAG" ]; then
-  #         echo "frontend release created"
-  #         else
-  #         echo "::error::frontend Realse was not created properly."
-  #         exit 1
-  #         fi
-
-  # TotF2Yr6r1ju9ZHp
+        LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]'
+  create-release:
+    needs: [deploy-prod]
+    name: create-release-from-tag
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout backend
+        uses: actions/checkout@v3
+      - name: Checkout shared actions
+        uses: actions/checkout@v3
+        with:
+          repository: Workiz/workiz-actions
+          ref: workiz.com
+          token: ${{ secrets.GH_TOKEN_MARKIZ_BOT }}
+          path: ./tmp/workiz-actions
+      - name: create backend release
+        run: | 
+          git config --global --add safe.directory /github/workspace
+          git fetch --tags
+          LAST_TAG=$(git tag | sort -V | grep -i "^v[0-9]\..*" | tail -1)
+          git_refs_response=$(
+          curl -s -X POST https://api.github.com/repos/Workiz/backend/releases \
+          -H "Authorization: token ${{ secrets.GH_TOKEN_REPOS }}" \
+          -d @- << EOF
+          {
+          "tag_name":"$LAST_TAG"
+          }
+          EOF
+          )
+          git_ref_posted=$( echo "${git_refs_response}" | jq .tag_name | tr -d '"' )
+          echo "::debug::${git_refs_response}"
+          if [ "${git_ref_posted}" = "$LAST_TAG" ]; then
+          echo "backend release created"
+          else
+          echo "::error::backend Realse was not created properly."
+          exit 1
+          fi
+      - name: Send failure slack msg 
+        if: failure()  
+        uses: ./tmp/workiz-actions/slack-msg
+        with:
+          CHANNEL: 'nehora'
+          MESSAGE: 'Failed to create GitHub release :sob:'
+          SUCCESS: false
+          WORKIZ_INFRA_AUTH: ${{ secrets.WORKIZ_INFRA_AUTH }}
+          LINKS: '[{"name" :"github-action","link": "https://github.com/Workiz/backend/actions/runs/${{github.run_id}}"}]' 
